title: Mental/Behavioral Health Resources
description: Resources for Mental/Behavioral Health
theme: just-the-docs

url: https:/mncare.github.io/mental-behvaioral-health-resources

aux_links: # remove if you don't want this link to appear on your pages
 Minnesota Community Care: https://www.mncare.org/minnesota-health-care-services/mental-health/
